#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="./tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_name="$2"

    echo "Fetching $buildpack_name..."

    set +e
    git clone "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name"; \
    pushd $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
        git fetch --quiet --tags; buildpack_commit=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=0 --max-count=1)); \
        git checkout --quiet "$buildpack_commit"
    popd &>/dev/null; \
    echo "Buildpack version: $buildpack_commit"

    echo "Done."
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack https://github.com/heroku/heroku-buildpack-multi.git          01-multi
download_buildpack https://github.com/heroku/heroku-buildpack-clojure.git        02-clojure
download_buildpack https://github.com/heroku/heroku-buildpack-go.git             03-go
download_buildpack https://github.com/heroku/heroku-buildpack-gradle.git         04-gradle
download_buildpack https://github.com/heroku/heroku-buildpack-grails.git         05-grails
download_buildpack https://github.com/heroku/heroku-buildpack-java.git           06-java
download_buildpack https://github.com/heroku/heroku-buildpack-nodejs.git         07-nodejs
download_buildpack https://github.com/heroku/heroku-buildpack-php.git            08-php
download_buildpack https://github.com/heroku/heroku-buildpack-play.git           09-play
download_buildpack https://github.com/heroku/heroku-buildpack-python.git         10-python
download_buildpack https://github.com/heroku/heroku-buildpack-ruby.git           11-ruby
download_buildpack https://github.com/heroku/heroku-buildpack-scala.git          12-scala
